language: julia
os:
    - linux
    - osx
julia:
    - 1.2
    - 1.3
    - nightly
matrix:
    allow_failures:
        - julia: [nightly]
        - os: osx
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - travis_wait 20 julia --project=@. --color=yes -e 'using Pkg;
                            Pkg.activate();
                            println("Activate");
                            Pkg.instantiate();
                            println("Instantiate");                            
                            Pkg.test(coverage=true)';
after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("NeuralQuantum")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.activate();
                                    Pkg.add("Documenter");
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
