language: julia
os:
    - linux
    - osx
julia:
    - 1.1
    - 1.2
    - 1.3
    - nightly
matrix:
    allow_failures:
        - julia: [1.3, nightly]
        - os: osx
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - travis_wait 20 julia --color=yes -e 'using Pkg;
                            Pkg.activate();
                            Pkg.add([PackageSpec(url="https://github.com/PhilipVinc/QuantumLattices.jl"),
                            PackageSpec(url="https://github.com/PhilipVinc/ValueHistoriesLogger.jl"),
                            Pkg.add(PackageSpec(name="Zygote", rev="master")),
                            Pkg.add(PackageSpec(name="ZygoteRules", rev="master"))]);
                            println("Installed [QuantumLattices, Zygote]");
                            Pkg.instantiate();
                            println("Instantiated");
                            println("Developed");
                            Pkg.test(coverage=true)';
after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("NeuralQuantum")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.add([PackageSpec(url="https://github.com/PhilipVinc/QuantumLattices.jl")]);
                                    Pkg.add("Documenter");
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
