name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: "Setup Julia environment ${{ matrix.julia-version }}"
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Cache MPI installation
        id: cache-mpi
        uses: actions/cache@v1
        with:
          path: ~/mpich
          key: ${{ runner.os }}-mpi
      - name: Install MPI
        if: steps.cache-mpi.outputs.cache-hit != 'true'
        run: sh ./conf/travis-install-mpi.sh mpich
      - name: Install Julia dependencies
        run: export JULIA_MPI_PATH=$HOME/mpich && julia --color=yes --project=@. -e 'using Pkg; Pkg.instantiate()'
      - name: Run Tests
        run: julia --color=yes --project=@. -e "using Pkg; Pkg.test(coverage=true)"
