name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Setup Julia environment ${{ matrix.julia-version }}"
        uses: julia-actions/setup-julia@v1.0.1
        with:
          version: ${{ matrix.julia-version }}
      - name: "Run Tests"
        run: |
            julia --color=yes --project=@. -e 'using Pkg;
                            Pkg.activate();
                            Pkg.instantiate();
                            println("Instantiated");'
            julia --color=yes --project=@. -e "using Pkg; Pkg.test(coverage=true)"
