name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: "Setup Julia environment ${{ matrix.julia-version }}"
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: "Install MPI"
        run: sh ./conf/travis-install-mpi.sh mpich
      - name: "Install Julia dependencies"
        run: echo $JULIA_MPI_PATH && export JULIA_MPI_PATH=$HOME/mpich && julia --color=yes --project=@. -e 'using Pkg; Pkg.instantiate()'
      - name: "Run Tests"
        run: julia --color=yes --project=@. -e "using Pkg; Pkg.test(coverage=true)"
